### PR TITLE
fix: outgoing TLS connections, `localhost` handling

### LINKED ISSUE #2134: [Bug]: TLS "connect" socket I/O occasionally succeeds (and usually fails)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

Occasional
```
Caused by:
    Resource temporarily unavailable (os error 6)
Error: failed to execute default function
```

When using

```toml
[[files]]
name = "api.github.com"
kind = "connect"
prot = "tls"
port = 443
host = "api.github.com"
```

### Expected Behaviour

Consistent success

### Environment Information

enarx 0.6.3

### Steps To Reproduce

_No response_

### PR DESCRIPTION
**Pull request by rvolosatovs**
Closes #2134 
Unit testing outgoing TLS requires #2170 

~Blocked by #2204~

Original implementation tested with https://github.com/enarx/codex/pull/53

### CODE REVIEW

**Comment by npmccallum** [comment]
@rvolosatovs It seems like we need a test case for this in order to test both the blocking and non-blocking cases.

**Comment by rvolosatovs** [comment]
> @rvolosatovs It seems like we need a test case for this in order to test both the blocking and non-blocking cases.

done, although that required quite a few changes in `exec-wasmtime` and implementing #2170 along the way

**Comment by rvolosatovs** [comment]
I extracted a few commits from this PR into separate PRs
- #2189
- #2190 
- #2191 
- #2192 
- #2193 
- #2194 
- #2195

**Comment by rvolosatovs** [comment]
now also https://github.com/enarx/enarx/pull/2196

**Comment by rvolosatovs** [comment]
Interesting Windows CI failure:
```

failures:

---- wasm::listen_tcp stdout ----
waiting for workload to start...
thread '<unnamed>' panicked at 'failed to connect to TCP socket: Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }', tests\wasm\mod.rs:437:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'wasm::listen_tcp' panicked at 'process timed out', tests\integration.rs:106:28

---- wasm::listen_tls stdout ----
waiting for workload to start...
thread '<unnamed>' panicked at 'failed to connect to TCP socket: Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }', tests\wasm\mod.rs:519:18
thread 'wasm::listen_tls' panicked at 'process timed out', tests\integration.rs:106:28


failures:
    wasm::listen_tcp
    wasm::listen_tls
```

will do some digging

File: crates/exec-wasmtime/src/runtime/net/tls.rs [hunk 1]
```diff
@@ -130,6 +131,7 @@ impl Stream {
         let mut stream = Self {
             tcp,
             tls,
+            nonblocking: false, // this is only valid under assumption that this executable has opened the socket
```
Comment (haraldh) [inline crates/exec-wasmtime/src/runtime/net/tls.rs:134]: you can query the current state of blocking with libc::fcntl(fd, libc::F_GETFL...) and check for O_NONBLOCK.

File: crates/exec-wasmtime/src/runtime/net/tls.rs [hunk 2]
```diff
@@ -270,7 +278,11 @@ impl WasiFile for Listener {
             .context("could not create new TLS connection")
             .map(Connection::Server)?;
 
-        let mut stream = Stream { tcp, tls };
+        let mut stream = Stream {
+            tcp,
+            tls,
+            nonblocking: false,
```
Comment (haraldh) [inline crates/exec-wasmtime/src/runtime/net/tls.rs:284]: you can query the current state of blocking with libc::fcntl(fd, libc::F_GETFL...) and check for O_NONBLOCK.

File: testdata/tls/ca.conf [hunk 3]
```diff
@@ -0,0 +1,16 @@
+[req]
```
Comment (haraldh) [inline testdata/tls/ca.conf:1]: please use the already existing `tests/data` rather than `testdata`

File: tests/crates/enarx_wasm_tests/src/bin/connect.rs [hunk 4]
```diff
@@ -0,0 +1,32 @@
...
+fn main() -> anyhow::Result<()> {
+    let fd_count: usize = env::var("FD_COUNT")
+        .context("failed to lookup `FD_COUNT`")?
+        .parse()
+        .context("failed to parse `FD_COUNT`")?;
+    ensure!(
+        fd_count == 4, // STDIN, STDOUT, STDERR and the socket connected to the endpoint
+        "unexpected amount of file descriptors received"
+    );
+    ensure!(
```
Comment (haraldh) [inline tests/crates/enarx_wasm_tests/src/bin/connect.rs:26]: out of curiosity, why `ensure!` and not `assert!` ??

File: tests/wasm/mod.rs [hunk 5]
```diff
@@ -15,7 +15,6 @@ use process_control::Output;
 use rustls::client::{ServerCertVerified, ServerCertVerifier};
 use rustls::version::TLS13;
 use rustls::Certificate;
-use serial_test::serial;
```
Comment (haraldh) [inline tests/wasm/mod.rs:12]: Why? Doesn't this then overload on SEV-SNP, which was the reason why we introduced this.

File: crates/exec-wasmtime/src/lib.rs [hunk 6]
```diff
@@ -105,14 +105,14 @@ mod test {
...
-        let mut file = NamedTempFile::new().context("failed to create module file")?;
+        let mut file = tempfile().context("failed to create module file")?;
         file.write(wasm).context("failed to write module to file")?;
         file.rewind().context("failed to rewind file")?;
         Runtime::execute(Package::Local {
             #[cfg(unix)]
-            wasm: (&file).as_raw_fd(),
+            wasm: file.as_raw_fd(),
             #[cfg(windows)]
-            wasm: file.into_file(),
```
Comment (haraldh) [inline crates/exec-wasmtime/src/lib.rs:115]: well, I guess, you could have use `NamedTempFile`, if you kept the result of `file.into_file()` in scope as long as the file is needed.
```rust
{ // scope start
   let wasm_file = file.into_file();
   Runtime::execute(Package::Local /* ... */)
} // scope end, wasm_file gets deleted by `drop`
```

**Review by haraldh — CHANGES_REQUESTED** [review]

File: Cargo.toml [hunk 7]
```diff
@@ -84,6 +84,7 @@ protobuf-codegen-pure = { version = "2.27", default-features = false }
 
 [dev-dependencies]
 process_control = { version = "3.3", default-features = false }
+rustls = { version = "0.20.6", default-features = false, features = ["dangerous_configuration"] }
```
[the remark this answers is not in the document]
Comment (rvolosatovs) [reply Cargo.toml:87]: This is only used for testing, specifically to allow self-signed certs

File: crates/exec-wasmtime/src/runtime/net/tls.rs (hunk 1 above)
Comment (rvolosatovs) [reply crates/exec-wasmtime/src/runtime/net/tls.rs:134]: Right, but we're opening the socket ourselves, why do a syscall?

File: testdata/tls/ca.conf (hunk 3 above)
Comment (rvolosatovs) [reply testdata/tls/ca.conf:1]: We already use `testdata` in https://github.com/profianinc/steward and https://github.com/profianinc/drawbridge. It would really want to have these all in one consistent location.

I'll move current files to `tests/data` and file an issue about it

File: tests/crates/enarx_wasm_tests/src/bin/connect.rs (hunk 4 above)
Comment (rvolosatovs) [reply tests/crates/enarx_wasm_tests/src/bin/connect.rs:26]: Panics are much more difficult to debug, than errors

File: tests/wasm/mod.rs (hunk 5 above)
Comment (rvolosatovs) [reply tests/wasm/mod.rs:12]: So far it looks like it works fine.

Without this, tests consistently time out and take forever locally.
Tests are only useful if they are simple to run and run fast.

Is there a config I can use, which would only enable this on SEV?

File: crates/exec-wasmtime/src/lib.rs (hunk 6 above)
Comment (rvolosatovs) [reply crates/exec-wasmtime/src/lib.rs:115]: Yes, but we don't need `NamedTempFile` and `tempfile()` is the preferred option.

> When choosing between the temporary file variants, prefer `tempfile` unless you either need to know the file’s path or to be able to persist it.

https://docs.rs/tempfile/latest/tempfile/index.html#design

File: crates/exec-wasmtime/src/runtime/net/tls.rs (hunk 2 above)
Comment (rvolosatovs) [reply crates/exec-wasmtime/src/runtime/net/tls.rs:284]: Yes, but we don't need to do that

File: crates/exec-wasmtime/src/runtime/net/tls.rs (hunk 1 above)
Comment (haraldh) [reply crates/exec-wasmtime/src/runtime/net/tls.rs:134]: ok

File: crates/exec-wasmtime/src/runtime/net/tls.rs (hunk 2 above)
Comment (rvolosatovs) [reply crates/exec-wasmtime/src/runtime/net/tls.rs:284]: We're unsetting any flags below anyway (as suggested by `man 2 accept`):
> On Linux, the new socket returned by accept() does not inherit file status flags such as O_NONBLOCK and O_ASYNC from the listening socket.  This behavior differs from the canonical BSD sockets implementation.  Portable programs should not rely on inheritance or noninheritance of file status flags and always explicitly set all required flags on the socket returned from accept().

File: tests/wasm/mod.rs (hunk 5 above)
Comment (haraldh) [reply tests/wasm/mod.rs:12]: ok, fine for now... we can reintroduce it, if it causes unexpected failures.

File: testdata/tls/ca.conf (hunk 3 above)
Comment (rvolosatovs) [reply testdata/tls/ca.conf]: Well, since we are nesting these in different subcrates, maybe it's fine as is

**Review by haraldh — APPROVED** [review]
