### PR TITLE
fix: make shims `cargo test --workspace` compatible

### LINKED ISSUE #1824: [Bug]: `cargo test --workspace` broken
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Current Behaviour

```
cargo test --workspace                 
   Compiling ureq v2.4.0
   Compiling rust_syscall_tests v0.1.0 (/home/rvolosatovs/src/github.com/enarx/enarx/tests/rust_syscall_tests)
error[E0152]: found duplicate lang item `panic_impl`
 --> tests/rust_syscall_tests/src/bin/read.rs:7:1
  |
7 | rust_syscall_tests::startup!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: the lang item is first defined in crate `std` (which `test` depends on)
  = note: first definition in `std` loaded from /nix/store/5p5rcbrpm5gbijy62qgk3892pnd9avgl-rust-std-nightly-2022-05-03/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-202fc93d8ccaebf2.so, /nix/store/5p5rcbrpm5gbijy62qgk3892pnd9avgl-rust-std-nightly-2022-05-03/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-202fc93d8ccaebf2.rlib
  = note: second definition in the local crate (`read`)
  = note: this error originates in the macro `rust_syscall_tests::startup` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0152]: found duplicate lang item `panic_impl`
 --> tests/rust_syscall_tests/src/bin/close.rs:7:1
  |
7 | rust_syscall_tests::startup!();
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: the lang item is first defined in crate `std` (which `test` depends on)
  = note: first definition in `std` loaded from /nix/store/5p5rcbrpm5gbijy62qgk3892pnd9avgl-rust-std-nightly-2022-05-03/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-202fc93d8ccaebf2.so, /nix/store/5p5rcbrpm5gbijy62qgk3892pnd9avgl-rust-std-nightly-2022-05-03/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-202fc93d8ccaebf2.rlib
  = note: second definition in the local crate (`close`)
  = note: this error originates in the macro `rust_syscall_tests::startup` (in Nightly builds, run with -Z macro-backtrace for more info)
```
And more like this

### Expected Behaviour

Passing tests of all crates within the workspace

### Environment Information

```
$ uname -a
Linux cobalt 5.17.2-zen3 #1-NixOS ZEN SMP PREEMPT Tue Jan 1 00:00:00 UTC 1980 x86_64 GNU/Linux
```

### Steps To Reproduce

_No response_

### PR DESCRIPTION
**Pull request by haraldh**
Closes #1824 

Signed-off-by: Harald Hoyer <harald@profian.com>

### CODE REVIEW

**Comment by rvolosatovs** [comment]
```
$ curl -sL https://github.com/enarx/enarx/pull/2423.patch | git am -3
$ cargo test --workspace --all-targets -j 8                           
   Compiling sallyport v0.6.4 (/home/rvolosatovs/src/github.com/enarx/enarx/crates/sallyport)
   Compiling enarx_syscall_tests v0.1.0 (/home/rvolosatovs/src/github.com/enarx/enarx/tests/crates/enarx_syscall_tests)
   Compiling enarx-shim-kvm v0.6.4 (/home/rvolosatovs/src/github.com/enarx/enarx/crates/shim-kvm)
   Compiling enarx-shim-sgx v0.6.4 (/home/rvolosatovs/src/github.com/enarx/enarx/crates/shim-sgx)
   Compiling enarx-config v0.6.4 (/home/rvolosatovs/src/github.com/enarx/enarx/crates/enarx-config)
   Compiling enarx_wasm_tests v0.1.0 (/home/rvolosatovs/src/github.com/enarx/enarx/tests/crates/enarx_wasm_tests)
   Compiling enarx-exec-wasmtime v0.6.4 (/home/rvolosatovs/src/github.com/enarx/enarx/crates/exec-wasmtime)
   Compiling enarx_exec_tests v0.1.0 (/home/rvolosatovs/src/github.com/enarx/enarx/tests/crates/enarx_exec_tests)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcAUKzYq/symbols.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673.17s367up2hw4vsnz.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673.191pws982k0v1uwa.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673.1yrsoywsyvdxo8af.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673.2moq57c95tvw2kjb.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673.4t1hfqqb3f5pam0b.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673.letsbm2qs243u1c.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673.5258gu487j32uvzr.rcgu.o" "-Wl,--as-needed" "-L" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps" "-L" "/nix/store/jg0s9yfjzx9mp344dg3psyyizl0ag3zy-rust-minimal-1.68.0-nightly-2022-12-14/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-a9f1acb017546b78.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-00cac95485657ff5.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-4d542c46f13f0370.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-90299a6a5f4fc776.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libnoted-46790bb54814c5df.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libenarx_shim_kvm-0f5071a97e2f722f.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libaes_gcm-1db9e0423ece1f7e.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libctr-03570a36fccec717.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libghash-d134ab65b690706c.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libpolyval-0f7ee83d0d633c9d.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libopaque_debug-b3a531c9eb400c1f.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libuniversal_hash-6b8e3f902dc90535.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libsubtle-1650842c3a6e5364.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libaes-e0ca0837b3030b87.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcpufeatures-0e4ae3c9982639cc.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcipher-7414d24d286b4a62.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libinout-c34c7511a872a63d.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libaead-de6f4c273130f335.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcrypto_common-aa7c79cfed64d24d.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libgeneric_array-85d86da1a6a69f28.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libtypenum-ae91be759e5f8db3.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libxsave-9aebca4b40a9b175.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcrt0stack-d34aeb86a2b57927.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libspin-9f59f765c5a12979.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblock_api-c6bea19f72bcd334.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libscopeguard-ff2bb1f39834214d.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblset-880b3026a32ae5b6.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblinked_list_allocator-65085a1b91c3a77c.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libx86_64-5e323f9fec30fe26.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libvolatile-3454b4f73ac632f4.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libbit_field-cef47076aabb6298.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libnbytes-c7f04a636a183cff.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libsallyport-d5b1f8260b2abc3e.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libbitflags-05dfd5b5d1225bed.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libprimordial-039611336e39712b.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libconst_default-ce7f2b2706e73a9c.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/librcrt1-b425e19bc9a7d0b9.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libgoblin-e941d35a7d9c9944.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libplain-cc17607e7100a3d8.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblog-649c0bab8e97b8c8.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libvalue_bag-48ffcdd3814451d1.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcfg_if-90e3626e3c41eec3.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libscroll-3cc87cd98991acf8.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-62c4894b82797b30.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-21d882eb82e74d58.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-a7a4a5c38e3da2ad.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-e2b1fec37c9c19cd.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-f5128b1419f0c95a.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-41e9355081407ce3.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-3d69bc2ce2ff7508.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-bb4c6139d02b6b90.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-3990de10d3f2460e.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-3a23c05350b4d45c.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-c2c33bc29289b145.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-b3d80be3be44960e.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-d2581a381e26c54b.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-0ff401eab4233ffd.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6d46d38f739892fe.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-cb19371b39fc63d8.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-522518611024dce5.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-05898138a596088a.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-66b9c3ae5ff29c13.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/nix/store/jg0s9yfjzx9mp344dg3psyyizl0ag3zy-rust-minimal-1.68.0-nightly-2022-12-14/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /nix/store/z3l0b9fha7yj3xnwbf49kd69qc6d5l0d-binutils-2.38/bin/ld: /home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_kvm-e1b3a71654593673.letsbm2qs243u1c.rcgu.o: in function `_start':
          letsbm2qs243u1c:(.reset+0x0): multiple definition of `_start'; /nix/store/cynvahq5hc4g8hg99vajx6p1gw7sqhm7-glibc-2.34-210/lib/Scrt1.o:/build/glibc-2.34/csu/../sysdeps/x86_64/start.S:63: first defined here
          /nix/store/z3l0b9fha7yj3xnwbf49kd69qc6d5l0d-binutils-2.38/bin/ld: /nix/store/cynvahq5hc4g8hg99vajx6p1gw7sqhm7-glibc-2.34-210/lib/Scrt1.o: in function `_start':
          /build/glibc-2.34/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `enarx-shim-kvm` due to previous error
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/rustcqKlBXx/symbols.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.168tdrgp9u5acjuu.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.1i90hzhy41oiwydn.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.1v6isvgtkb7gks0x.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.31s665khvckpfd7d.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.3kgtpnbq7021ylad.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.3p9tsvdv6zv68yfg.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.3r6vc83gm48e9h2g.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.5a405jfa72804zsw.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.iav7qtc5tih9wze.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.ic9kucwk27ufe42.rcgu.o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.3oynds8m3k73f2o9.rcgu.o" "-Wl,--as-needed" "-L" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps" "-L" "/nix/store/jg0s9yfjzx9mp344dg3psyyizl0ag3zy-rust-minimal-1.68.0-nightly-2022-12-14/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-a9f1acb017546b78.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-00cac95485657ff5.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunicode_width-4d542c46f13f0370.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_std-90299a6a5f4fc776.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libnoted-46790bb54814c5df.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libenarx_shim_sgx-416eca3c25f6f367.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libspin-9f59f765c5a12979.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblock_api-c6bea19f72bcd334.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libscopeguard-ff2bb1f39834214d.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libmmledger-2945f81c6255d5b8.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libprimordial-039611336e39712b.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblset-880b3026a32ae5b6.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libsgx-b0a334c11abb9262.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libxsave-9aebca4b40a9b175.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libx86_64-5e323f9fec30fe26.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libvolatile-3454b4f73ac632f4.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libbit_field-cef47076aabb6298.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libsha2-b9da4a8a9c5cff18.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcpufeatures-0e4ae3c9982639cc.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/librsa-13fa3895a556f31f.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libpkcs1-3ac16c61a36ab759.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libpkcs8-7da943898ccf7c64.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libspki-e6de20093539ade9.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libder-02111511ef6d5c6a.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libpem_rfc7468-367df4b1ccf30814.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libbase64ct-5e26f2dd4e617945.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libconst_oid-adea344c9b3f550d.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcrypto_bigint-f4aff2f83861b797.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libdigest-2505bf52ebb3febf.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libsubtle-1650842c3a6e5364.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libblock_buffer-d8674039147d6dce.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcrypto_common-aa7c79cfed64d24d.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libgeneric_array-85d86da1a6a69f28.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libtypenum-ae91be759e5f8db3.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libnum_bigint_dig-bafe93cd6286a9f1.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblibm-11fb768c3f50871d.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libnum_iter-2948e74496d878fd.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libbyteorder-4d098c56eb4115f5.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libzeroize-bb68e3279a603106.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblazy_static-fa830f1fafdc889c.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libspin-2c2d0e97c8363747.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libsmallvec-1bab1a7cb55a60d2.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/librand-541021ad4dfcfcdf.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/librand_chacha-07fb0e0ad53001ba.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libppv_lite86-5e6fdfabf1edbf66.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/librand_core-c81bfe403e48d9b3.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libgetrandom-1f8abfe8a9274130.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblibc-2ddc04b21f426065.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libnum_integer-cd9a74dacb2cbc22.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libnum_traits-87590c3c0acc5269.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libsallyport-d5b1f8260b2abc3e.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libbitflags-05dfd5b5d1225bed.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcrt0stack-d34aeb86a2b57927.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libconst_default-ce7f2b2706e73a9c.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/librcrt1-b425e19bc9a7d0b9.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libgoblin-e941d35a7d9c9944.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libplain-cc17607e7100a3d8.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/liblog-649c0bab8e97b8c8.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libvalue_bag-48ffcdd3814451d1.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libcfg_if-90e3626e3c41eec3.rlib" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/libscroll-3cc87cd98991acf8.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-62c4894b82797b30.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-21d882eb82e74d58.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-a7a4a5c38e3da2ad.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-e2b1fec37c9c19cd.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-f5128b1419f0c95a.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-41e9355081407ce3.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-3d69bc2ce2ff7508.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-bb4c6139d02b6b90.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-3990de10d3f2460e.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-3a23c05350b4d45c.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-c2c33bc29289b145.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-b3d80be3be44960e.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-d2581a381e26c54b.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-0ff401eab4233ffd.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6d46d38f739892fe.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-cb19371b39fc63d8.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-522518611024dce5.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-05898138a596088a.rlib" "/nix/store/3b7bi0z8myhc45bbwlhk28c9ikmhw06c-rust-std-1.68.0-nightly-2022-12-14-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-66b9c3ae5ff29c13.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/nix/store/jg0s9yfjzx9mp344dg3psyyizl0ag3zy-rust-minimal-1.68.0-nightly-2022-12-14/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: /nix/store/z3l0b9fha7yj3xnwbf49kd69qc6d5l0d-binutils-2.38/bin/ld: /home/rvolosatovs/src/github.com/enarx/enarx/target/debug/deps/enarx_shim_sgx-f1676475fb2f9741.1v6isvgtkb7gks0x.rcgu.o: in function `_start':
          1v6isvgtkb7gks0x:(.text.startup+0x67): multiple definition of `_start'; /nix/store/cynvahq5hc4g8hg99vajx6p1gw7sqhm7-glibc-2.34-210/lib/Scrt1.o:/build/glibc-2.34/csu/../sysdeps/x86_64/start.S:63: first defined here
          /nix/store/z3l0b9fha7yj3xnwbf49kd69qc6d5l0d-binutils-2.38/bin/ld: /nix/store/cynvahq5hc4g8hg99vajx6p1gw7sqhm7-glibc-2.34-210/lib/Scrt1.o: in function `_start':
          /build/glibc-2.34/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `enarx-shim-sgx` due to previous error
cargo test --workspace --all-targets -j 8  29.31s user 9.47s system 308% cpu 12.562 total
```

**Comment by rvolosatovs** [comment]
This works, but:
```
warning: unused import: `core::mem::MaybeUninit`
  --> crates/shim-sgx/src/main.rs:20:5
   |
20 | use core::mem::MaybeUninit;
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `core::ptr::NonNull`
  --> crates/shim-sgx/src/main.rs:21:5
   |
21 | use core::ptr::NonNull;
   |     ^^^^^^^^^^^^^^^^^^

warning: unused imports: `LoadRegsExt`, `NEW_THREAD_QUEUE`, `NewThreadFromRegisters`, `NewThread`, `THREADS_FREE`, `Tcb`
  --> crates/shim-sgx/src/main.rs:25:5
   |
25 |     LoadRegsExt, NewThread, NewThreadFromRegisters, Tcb, NEW_THREAD_QUEUE, THREADS_FREE,
   |     ^^^^^^^^^^^  ^^^^^^^^^  ^^^^^^^^^^^^^^^^^^^^^^  ^^^  ^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^

warning: unused imports: `CSSA_0_STACK_SIZE`, `ENARX_EXEC_START`, `NUM_SSA`, `entry`, `handler`
  --> crates/shim-sgx/src/main.rs:28:5
   |
28 |     entry, handler, shim_address, ATTR, BLOCK_SIZE, CSSA_0_STACK_SIZE, ENARX_EXEC_START,
   |     ^^^^^  ^^^^^^^                                  ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^
29 |     ENARX_SHIM_ADDRESS, ENCL_SIZE, ENCL_SIZE_BITS, MISC, NUM_SSA,
   |                                                          ^^^^^^^

warning: unused import: `primordial::Page`
  --> crates/shim-sgx/src/main.rs:32:5
   |
32 | use primordial::Page;
   |     ^^^^^^^^^^^^^^^^

warning: unused imports: `GenPurposeRegs`, `StateSaveArea`
  --> crates/shim-sgx/src/main.rs:36:16
   |
36 | use sgx::ssa::{GenPurposeRegs, StateSaveArea};
   |                ^^^^^^^^^^^^^^  ^^^^^^^^^^^^^

warning: function `validate_block_ptr` is never used
   --> crates/shim-sgx/src/main.rs:280:4
    |
280 | fn validate_block_ptr(ptr: *mut u8) -> &'static mut [usize; BLOCK_SIZE / size_of::<usize>()] {
    |    ^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: function `clearx` is never used
  --> crates/shim-sgx/src/main.rs:75:8
   |
75 |     fn clearx();
   |        ^^^^^^

warning: function `clearp` is never used
   --> crates/shim-sgx/src/main.rs:112:8
    |
112 |     fn clearp();
    |        ^^^^^^

warning: function `relocate` is never used
   --> crates/shim-sgx/src/main.rs:142:8
    |
142 |     fn relocate();
    |        ^^^^^^^^

warning: unused import: `enarx_shim_kvm::addr::SHIM_VIRT_OFFSET`
  --> crates/shim-kvm/src/main.rs:17:5
   |
17 | use enarx_shim_kvm::addr::SHIM_VIRT_OFFSET;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `enarx_shim_kvm::exec`
  --> crates/shim-kvm/src/main.rs:18:5
   |
18 | use enarx_shim_kvm::exec;
   |     ^^^^^^^^^^^^^^^^^^^^

warning: unused import: `enarx_shim_kvm::gdt`
  --> crates/shim-kvm/src/main.rs:19:5
   |
19 | use enarx_shim_kvm::gdt;
   |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `enarx_shim_kvm::interrupts`
  --> crates/shim-kvm/src/main.rs:21:5
   |
21 | use enarx_shim_kvm::interrupts;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused imports: `PDPT`, `PDT_C000_0000`, `PML4T`, `PT_FFE0_0000`, `unmap_identity`
  --> crates/shim-kvm/src/main.rs:22:34
   |
22 | use enarx_shim_kvm::pagetables::{unmap_identity, PDPT, PDT_C000_0000, PML4T, PT_FFE0_0000};
   |                                  ^^^^^^^^^^^^^^  ^^^^  ^^^^^^^^^^^^^  ^^^^^  ^^^^^^^^^^^^

warning: unused import: `enarx_shim_kvm::print::enable_printing`
  --> crates/shim-kvm/src/main.rs:23:5
   |
23 | use enarx_shim_kvm::print::enable_printing;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `enarx_shim_kvm::snp::C_BIT_MASK`
  --> crates/shim-kvm/src/main.rs:24:5
   |
24 | use enarx_shim_kvm::snp::C_BIT_MASK;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `enarx_shim_kvm::sse`
  --> crates/shim-kvm/src/main.rs:25:5
   |
25 | use enarx_shim_kvm::sse;
   |     ^^^^^^^^^^^^^^^^^^^

warning: unused import: `global_asm`
  --> crates/shim-kvm/src/main.rs:27:23
   |
27 | use core::arch::{asm, global_asm};
   |                       ^^^^^^^^^^

warning: unused import: `core::mem::size_of`
  --> crates/shim-kvm/src/main.rs:28:5
   |
28 | use core::mem::size_of;
   |     ^^^^^^^^^^^^^^^^^^

warning: unused import: `core::sync::atomic::Ordering`
  --> crates/shim-kvm/src/main.rs:29:5
   |
29 | use core::sync::atomic::Ordering;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `rcrt1::dyn_reloc`
  --> crates/shim-kvm/src/main.rs:34:5
   |
34 | use rcrt1::dyn_reloc;
   |     ^^^^^^^^^^^^^^^^

warning: unused imports: `Cr0Flags`, `Cr4Flags`, `EferFlags`
  --> crates/shim-kvm/src/main.rs:36:34
   |
36 | use x86_64::registers::control::{Cr0Flags, Cr4Flags, EferFlags};
   |                                  ^^^^^^^^  ^^^^^^^^  ^^^^^^^^^

warning: unused macro definition: `set_table_c_bit`
   --> crates/shim-kvm/src/main.rs:170:14
    |
170 | macro_rules! set_table_c_bit {
    |              ^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_macros)]` on by default

warning: unused macro definition: `correct_table_c_bit`
   --> crates/shim-kvm/src/main.rs:184:14
    |
184 | macro_rules! correct_table_c_bit {
    |              ^^^^^^^^^^^^^^^^^^^

warning: function `switch_shim_stack` is never used
  --> crates/shim-kvm/src/main.rs:84:11
   |
84 | unsafe fn switch_shim_stack(ip: extern "sysv64" fn() -> !, sp: u64) -> ! {
   |           ^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
 ```

File: crates/shim-kvm/build.rs [hunk 1]
```diff
@@ -1,10 +1,15 @@
...
-    println!("cargo:rustc-link-arg-bin=enarx-shim-kvm=-nostartfiles");
+    let target_os = var("CARGO_CFG_TARGET_OS").expect("missing CARGO_CFG_TARGET_OS");
+    if target_os == "none" {
+        println!(
+            "cargo:rustc-link-arg-bin=enarx-shim-kvm=-T{}/layout.ld",
+            std::env::var("CARGO_MANIFEST_DIR").unwrap()
+        );
+        println!("cargo:rustc-link-arg-bin=enarx-shim-kvm=-Wl,--sort-section=alignment");
+        println!("cargo:rustc-link-arg-bin=enarx-shim-kvm=-nostartfiles");
+    }
```
Comment (rvolosatovs) [inline crates/shim-kvm/build.rs:14]:
```suggestion
    if var("CARGO_CFG_TARGET_OS").expect("missing CARGO_CFG_TARGET_OS") == "none" {
        println!(
            "cargo:rustc-link-arg-bin=enarx-shim-kvm=-T{}/layout.ld",
            var("CARGO_MANIFEST_DIR").unwrap()
        );
        println!("cargo:rustc-link-arg-bin=enarx-shim-kvm=-Wl,--sort-section=alignment");
        println!("cargo:rustc-link-arg-bin=enarx-shim-kvm=-nostartfiles");
    }
```

File: crates/shim-sgx/build.rs [hunk 2]
```diff
@@ -1,10 +1,16 @@
...
+    let target_os = var("CARGO_CFG_TARGET_OS").expect("missing CARGO_CFG_TARGET_OS");
+
+    if target_os == "none" {
+        println!(
+            "cargo:rustc-link-arg-bin=enarx-shim-sgx=-T{}/layout.ld",
+            std::env::var("CARGO_MANIFEST_DIR").unwrap()
+        );
+        println!("cargo:rustc-link-arg-bin=enarx-shim-sgx=-Wl,--sort-section=alignment");
+        println!("cargo:rustc-link-arg-bin=enarx-shim-sgx=-nostartfiles");
+    }
```
Comment (rvolosatovs) [inline crates/shim-sgx/build.rs:15]:
```suggestion
     if var("CARGO_CFG_TARGET_OS").expect("missing CARGO_CFG_TARGET_OS") == "none" {
        println!(
            "cargo:rustc-link-arg-bin=enarx-shim-sgx=-T{}/layout.ld",
            var("CARGO_MANIFEST_DIR").unwrap()
        );
        println!("cargo:rustc-link-arg-bin=enarx-shim-sgx=-Wl,--sort-section=alignment");
        println!("cargo:rustc-link-arg-bin=enarx-shim-sgx=-nostartfiles");
    }
```

**Review by rvolosatovs — COMMENTED** [review]
Thanks for looking into this, minor comment and please look into fixing the "unused" warnings I posted

File: crates/shim-sgx/build.rs (hunk 2 above)
Comment (haraldh) [reply crates/shim-sgx/build.rs]: fixed

File: crates/shim-kvm/build.rs (hunk 1 above)
Comment (haraldh) [reply crates/shim-kvm/build.rs]: fixed

File: crates/shim-kvm/build.rs [hunk 3]
```diff
@@ -1,10 +1,14 @@
...
-    println!(
-        "cargo:rustc-link-arg-bin=enarx-shim-kvm=-T{}/layout.ld",
-        std::env::var("CARGO_MANIFEST_DIR").unwrap()
-    );
-    println!("cargo:rustc-link-arg-bin=enarx-shim-kvm=-Wl,--sort-section=alignment");
-    println!("cargo:rustc-link-arg-bin=enarx-shim-kvm=-nostartfiles");
+    if var("CARGO_CFG_TARGET_OS").expect("missing CARGO_CFG_TARGET_OS") == "none" {
+        println!(
+            "cargo:rustc-link-arg-bin=enarx-shim-kvm=-T{}/layout.ld",
+            std::env::var("CARGO_MANIFEST_DIR").unwrap()
```
Comment (rvolosatovs) [inline crates/shim-kvm/build.rs:9]:
```suggestion
            var("CARGO_MANIFEST_DIR").unwrap()
```

File: crates/shim-sgx/build.rs [hunk 4]
```diff
@@ -1,10 +1,14 @@
...
-    println!(
-        "cargo:rustc-link-arg-bin=enarx-shim-sgx=-T{}/layout.ld",
-        std::env::var("CARGO_MANIFEST_DIR").unwrap()
-    );
-    println!("cargo:rustc-link-arg-bin=enarx-shim-sgx=-Wl,--sort-section=alignment");
-    println!("cargo:rustc-link-arg-bin=enarx-shim-sgx=-nostartfiles");
+    if var("CARGO_CFG_TARGET_OS").expect("missing CARGO_CFG_TARGET_OS") == "none" {
+        println!(
+            "cargo:rustc-link-arg-bin=enarx-shim-sgx=-T{}/layout.ld",
+            std::env::var("CARGO_MANIFEST_DIR").unwrap()
```
Comment (rvolosatovs) [inline crates/shim-sgx/build.rs:9]:
```suggestion
            var("CARGO_MANIFEST_DIR").unwrap()
```

**Review by rvolosatovs — COMMENTED** [review]
Nice!
2 minor nits unaddressed from last review

**Review by rvolosatovs — APPROVED** [review]
